### PR TITLE
chore: use * import from leaflet

### PR DESCRIPTION
**Pull request by grigorpavlov**
I had an issue with the migration between different versions on angular 12 application

### CODE REVIEW

**Comment by rogerg93** [comment]
When can we expect this to be merged?

**Comment by smeijer** [comment]
Done, published as 3.5.1.

**Comment by smeijer** [comment]
@all-contributors please add @grigorpavlov for code

**Comment by gasparpd** [comment]
image

Import error still persist on SearchControl.d.ts. My app runs on Angular 11. I´ve tried lastest v3.5.1.

**Comment by smeijer** [comment]
Can you try `3.5.2`? I don't use Angular, so it's hard for me to try it myself.

**Comment by gasparpd** [comment]
> Can you try `3.5.2`? I don't use Angular, so it's hard for me to try it myself.

3.5.2 fixed that, thanks! It works perfectly.

**Comment by smeijer** [comment]
Sweet! Thanks for letting me know.

**Pull request merged**
