### PR TITLE
feat: improve labels of Algolia provider by using match level

### PR DESCRIPTION
**Pull request by yzinets**
Solution for #221

### CODE REVIEW

**Comment by smeijer** [comment]
Thanks for your pull-request @yzinets! Can you show me a before/after screenshot?

**Comment by yzinets** [comment]
Here are old results (an example of incorrect postcode in labels)

Screenshot 2020-05-28 at 21 09 01

And new one (corrected with match level)

Screenshot 2020-05-28 at 21 08 27

To be honest, I don't really think that this solution (code) is pretty much, but it solves this issue :)

Also, I'd like to create another one issue, related to docs and development process. It was a bit hard to make a screenshot on the local instance of docs (`npm run docz:dev` just gives an error in my case). It would be great to make some notes in readme for contributors.

**Comment by smeijer** [comment]
Aaah, I see. It's really just incorrect postal codes? Thanks! I'll merge.

About the dev, I understand. I think you should just use `npm run start`, and not `docz:dev`. If that doesn't work, (because of cross dependencies between build & docs), it might be necessary to run `npm run build` first.

**Comment by smeijer** [comment]
Merged and published as `leaflet-geosearch@3.0.5`. Again, thanks for your contribution :+1:

**Comment by smeijer** [comment]
Hi @yuriizinets, I've noticed your activity on this repo, and wanted to say thanks! 

I've added you as a collaborator on the project. 

You might also want to [watch the repo][watch] to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). 

Thanks! And welcome to the team :tada:  

[watch]: https://help.github.com/articles/watching-repositories

**Comment by yuriizinets** [comment]
Hi @smeijer , thank you for invite!
I'm already watching this repo :)
I'll help to handle some issues/tasks when will there be some free time, sometimes I have too much work. Anyway, I'll do my best!

Also, feel free to contact me via email if something is needed

**Pull request merged**
