### PR TITLE
Fix for google provider test

### PR DESCRIPTION
**Pull request by yzinets**
API Key is required now
- add an API key from env to provider in tests
- remove a test, related to fetching with API key
(fetching with key by default)

### CODE REVIEW

**Comment by yzinets** [comment]
@smeijer 
Please, can you provide a Google API Key in the Travis CI as an environment variable?
Suddenly, API Key is required by Google now.
Thank you very much!

**Comment by smeijer** [comment]
Does it require a payment (registration)?

**Comment by yzinets** [comment]
Yes, it requires registration. As I know, Google API has free tier, up to 70000 requests.
If it’s impossible, I can skip the test, depending on provided env (if api key is not provided, just skipping).
In that way, we will have ability to normally build that project in CI.
Please, notify me about your decision, I’ll do my best.

**Comment by smeijer** [comment]
Skipping the test if the key isn't provided, sounds fine for the time being.

That gives me some time to get a new api key and add it to CI.

**Comment by yzinets** [comment]
@smeijer Hi! 
Is there any update on this?
It's simple PR 🙂

**Comment by smeijer** [comment]
merged. Thanks

**Comment by yzinets** [comment]
@smeijer 
Thank you very much 🙏

**Pull request merged**
