### PR TITLE
Add OpenCage Provider

### PR DESCRIPTION
**Pull request by kaoru**
Add support for the OpenCage Geocoder (https://geocoder.opencagedata.com)

I followed the steps from https://github.com/smeijer/leaflet-geosearch/pull/143 so it was all fairly straightforward :grin: I tested with my personal OpenCage API key and the tests pass ok, but of course you should sign up and give it a go yourself :+1: 

The only thing I wasn't sure about is that LocationIQ's PR included some changes to files in `docs/dist/` - those files look automatically generated, what's the command to re-generate them? Why is there a `dist` and a `docs/dist/`?

Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by freyfogle** [comment]
Hi, any hope of getting this merged? thanks

**Comment by freyfogle** [comment]
Hi, 
something is preventing this PR from being merged. What is it? What can we do to move it forward? 
Thanks for your attention,
Ed

**Comment by smeijer** [comment]
Time, only the lack of time. See #172

**Comment by freyfogle** [comment]
ahh, had not seen that. 
Many thanks for merging, and for the project. I appreciate it

**Pull request merged**
