### PR TITLE
feat: add provider for https://civildefense.fit.vutbr.cz/search

### PR DESCRIPTION
**Pull request by xbarin02**
We develop new provider based on the data from [RÚIAN](https://www.cuzk.cz/ruian/RUIAN.aspx) service, which are intended for the Czech Republic. We would like to put our work into upstream. For any questions, please write to David Barina <ibarina@fit.vutbr.cz>. Thank you.

### CODE REVIEW

**Review by smeijer — APPROVED** [review]

**Comment by smeijer** [comment]
Thanks! Looks good.

**Comment by smeijer** [comment]
@all-contributors please add @xbarin02 for code

**Comment by ramazansancar** [comment]
Hello @xbarin02 (David Barina),
I'm having trouble with the reverse API endpoint. I would like to ask for your help with this.

The "search" endpoint is working fine. However, the "reverse" endpoint doesn't seem to be working, probably because it's no longer in use.

image

image

**Pull request merged**
