### PR TITLE
add query restriction option to open street map  provider

### PR DESCRIPTION
**Pull request by ahmdsamir91**

### CODE REVIEW

**Comment by smeijer** [comment]
Are the already supported (and native Nominatim) parameters insufficient? 

https://wiki.openstreetmap.org/wiki/Nominatim#Parameters

> **countrycodes**=<countrycode>[,<countrycode>][,<countrycode>]...
> 
> Limit search results to a specific country (or a list of countries).
<countrycode> should be the ISO 3166-1alpha2 code, e.g. gb for the United Kingdom, de for Germany, etc.
>
> **viewbox**=<x1>,<y1>,<x2>,<y2>
> 
> The preferred area to find search results. Any two corner points of the box are accepted in any order as long as they span a real box.

```js
// import
import { OpenStreetMapProvider } from 'leaflet-geosearch';

// setup
const provider = new OpenStreetMapProvider({
  params: {  
    viewbox: '...',
    countrycode: 'nl',
  }
});

// search
const results = await provider.search({ query: input.value });
```

**Comment by smeijer** [comment]
Even if that would be insufficient, wouldn't it be enough to wrap the `search` command?

```js
// search
const results = await provider.search({ query: input.value + ' your modifier' });
```

**Comment by ahmdsamir91** [comment]
> Are the already supported (and native Nominatim) parameters insufficient?
> 
> https://wiki.openstreetmap.org/wiki/Nominatim#Parameters
> 
> > **countrycodes**=[,][,]...
> > Limit search results to a specific country (or a list of countries).
> >  should be the ISO 3166-1alpha2 code, e.g. gb for the United Kingdom, de for Germany, etc.
> > **viewbox**=,,,
> > The preferred area to find search results. Any two corner points of the box are accepted in any order as long as they span a real box.
> 
> ```js
> // import
> import { OpenStreetMapProvider } from 'leaflet-geosearch';
> 
> // setup
> const provider = new OpenStreetMapProvider({
>   params: {  
>     viewbox: '...',
>     countrycode: 'nl',
>   }
> });
> 
> // search
> const results = await provider.search({ query: input.value });
> ```

i tried to add use the parameter but it didn't restrict the user query.
after search i found out that parameter and query doesn't work together you can only use one of them.




> Even if that would be insufficient, wouldn't it be enough to wrap the `search` command?
> 
> ```js
> // search
> const results = await provider.search({ query: input.value + ' your modifier' });
> ```

this will do it but i have to re redo all the customization you did the search-box.

i think it will a good feature to add restriction on the user query with out having to re-do the customization.

**Comment by smeijer** [comment]
My apologies for the long wait. I'm going to close this one, and will think of a solution on the higher level so that all providers can use some query manipulation before the request is being send. That solution will be tracked in #215.

At the same time, I've updated the docs to provide more information about how to limit results by using the providers' [optional parameters][1].

[1]: https://smeijer.github.io/leaflet-geosearch/providers/openstreetmap#optional-parameters 

Again, thanks for taking the trouble of opening a PR, and my apologies for the long wait.

**Pull request closed without merging**
